---
# RISC OS 64 update of Wiki for information
#
# The Wiki is updated with the changes from the status in the repository.
#

name: Wiki update

# Controls when the action will run. Triggers the workflow on:
#   * push on master.
on:
  push:
    branches: ["master"]

concurrency:
  # Be nice to the build service and only submit a single job at a time.
  group: wiki-update
  cancel-in-progress: false

jobs:
  wiki:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build all the documents
        run: |
          make all

      - name: Report on progress statistics
        run: |
          echo '# Progress statistics' >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          cat statistics.md >> $GITHUB_STEP_SUMMARY
          cp statistics.md wiki-update/Statistics.md

      - name: Report on progress of phase 1
        run: |
          echo >> $GITHUB_STEP_SUMMARY
          echo '---' >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo '# Progress of phase 1' >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo '```mermaid' >> $GITHUB_STEP_SUMMARY
          cat planning/Phase-1.mmd >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY

      # See: https://github.com/marketplace/actions/wiki-page-creator-action
      - name: Upload documents to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          ACTION_MAIL: gerph@gerph.org
          ACTION_NAME: Charles Ferguson
          OWNER: gerph
          REPO_NAME: riscos64-status
          MD_FOLDER: wiki-update

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: RISC OS 64 Progress
          path: |
            statistics*
            plan*.*
            planning/*.mmd
            planning/*.svg

      # https://github.com/marketplace/actions/deploy-to-gist
      - name: Upload percentages as gists (Phase 1)
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_PAT }}
          gist_id: c26e8457269506554ec1f7533d2f9aed
          gist_file_name: Progress-1.svg
          file_path: planning/Progress-1.svg
          file_type: text

      - name: Sleep to prevent races
        run: |
          sleep 4

      - name: Upload percentages as gists (Phase 2)
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_PAT }}
          gist_id: c26e8457269506554ec1f7533d2f9aed
          gist_file_name: Progress-2.svg
          file_path: planning/Progress-2.svg
          file_type: text

      - name: Sleep to prevent races
        run: |
          sleep 4

      - name: Upload percentages as gists (Phase 3)
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_PAT }}
          gist_id: c26e8457269506554ec1f7533d2f9aed
          gist_file_name: Progress-3.svg
          file_path: planning/Progress-3.svg
          file_type: text

      - name: Sleep to prevent races
        run: |
          sleep 4

      - name: Upload percentages as gists (Phase 4)
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_PAT }}
          gist_id: c26e8457269506554ec1f7533d2f9aed
          gist_file_name: Progress-4.svg
          file_path: planning/Progress-4.svg
          file_type: text

      - name: Sleep to prevent races
        run: |
          sleep 4

      - name: Upload percentages as gists (Phase 5)
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_PAT }}
          gist_id: c26e8457269506554ec1f7533d2f9aed
          gist_file_name: Progress-5.svg
          file_path: planning/Progress-5.svg
          file_type: text

      - name: Sleep to prevent races
        run: |
          sleep 4

      - name: Upload percentages as gists (Phase 6)
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_PAT }}
          gist_id: c26e8457269506554ec1f7533d2f9aed
          gist_file_name: Progress-6.svg
          file_path: planning/Progress-6.svg
          file_type: text

      - name: Sleep to prevent races
        run: |
          sleep 4

      - name: Upload percentages as gists (Phase 7)
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_PAT }}
          gist_id: c26e8457269506554ec1f7533d2f9aed
          gist_file_name: Progress-7.svg
          file_path: planning/Progress-7.svg
          file_type: text
